### ISSUE TITLE
Low Fps

### ISSUE THREAD

**Issue by Astrallys** [toolboc/UWPStreamer#1]
Hello,

First thanks for the good work ( i used both version )
But UWPStream as only low  fps. And ( i think you have stopped working on it ) but can you add an fps counter ?

Also which version is up to date ? The precompiled exe or the one from the windows store ? ( because there is not the same )

**Comment by toolboc** [comment]
FPS can be due to a variety of factors, I have not added a counter although it should be pretty straightforward to do so.  I would be happy to accept a PR here.

The releases (both UWP and WPF edition) are both latest.  They are two separate releases.

Thank you for using the software!  I hope it is useful to you =)

**Comment by Astrallys** [comment]
well, the low fps are only with UWPStreamer.. Watever the settings i used. ( compared to kit-kat ) the fps are always bad here :/

**Comment by toolboc** [comment]
Curious, what are the settings that you are using with UWPStreamer?

**Comment by Astrallys** [comment]
all of those settings ( there is the settings is use with kit kat and try with UWPStreamer ) but with UWPStreamer i can't get 30fps :/ 
Image quality / Priority Factor // QoS Value 
90 - 5 - 45 = 33-26
90 - 5 - 101 - 1 = 30-37
90 - 0 - 100 - 1 = 30-37
80 - 2 - 100 - 1 = 38-43			Bottom Screen Scale 0 //
95 - 2 - 100 - 1 = 30-35
50 - 1 - 101 - 0 = 40-45 fps			Bottom Screen Scale 0
70 - 1 - 101 - 0 = 40-45 fps			Bottom Screen Scale 0
80 - 1 - 101 - 0 = 38-40 fps			Bottom Screen Scale 0
80 - 1 - 20 - 0 = 30-35 fps			Bottom Screen Scale 0


the fps are the fps lsited are from kit-kat

**Comment by toolboc** [comment]
I will do my best to try to explain, although this may not directly answer your question.
Let's begin with a little background on NTR Streaming ;)

Apparently, NTR's internal handling of certain parameters goes against intuition.  
The following is taken from the comments [RattletraPM's NitroStreamer source code comments](https://github.com/RattletraPM/Snickerstream/blob/master/include/ntr.au3):

//_If this (QoS) value is higher than 100 then NTR simpli disables the QoS feature, so we just set it to an arbitrary value higher than 100_

This is interesting because your results seem to show highest performance when QoS is disabled due to being set above 100 (though this may be more due to reduction of image quality).

_Finally, byte 0x1A contains the QoS value. I have no idea why, but NTR expects it to be double its intended value._

For whatever reason, any client that sends over the QoS parameter to NTR needs to be aware of this.  UWPStreamer and WPFStreamer take this behavior into account.

During development I recall coming to a conclusion that Priority Factory is wholly dependent on it's implementation in the client.  I did my best to employ priority scheduling within UWPStreamer and WPFStreamer.  I recall that NitroStreamer handled this completely differently and may have made certain assumptions that may or may not be optimal (same goes for my implementation).  

Okay, so with some of the background out of the way, let's look at what should be assumed in UWPStreamer / WPFStreamer given the implementation used there:

1. Image Quality can drastically improve performance by tuning down.  Less data = less time for transmission and faster ability to produce frames

2. Priority Factor is directly related to the screen that is selected for the screen priority option (Top / Bottom).  Easiest way to explain is that if Top is selected as screen priority and Priority factor of X is chosen, NTR will send X frames of the priority screen before sending a packet containing frame data for the Bottom screen.  Be aware that this needs to be implemented appropriately in the client to drop bad frames and assemble good frames (frames are sent in multiple packets).  UWPStreamer handles this in the `NTRRemoteplayReadJPEG` method of [Services/NTR.cs](https://github.com/toolboc/UWPStreamer/blob/master/UWPStreamer/Services/NTR.cs)

3. QoS, to my understanding, requires a router capable of enforcing QoS and again requires the client to send double the intended value as mentioned above (due to internal handling by NTR itself).

Lastly, I have also seen [reports on Reddit that users sometimes get different performance between UWPStreamer and WPFStreamer](https://www.reddit.com/r/3dshacks/comments/5trkew/release_uwpstreamer_wpf_edition_net_462/ddoo74z/).  Oddly enough, the code is nearly identical in both releases with subtle differences in the way bytes are assembled to create image data from packets.  

I provided a possible explanation for this in an [/r/3dshacks thread](https://www.reddit.com/r/3dshacks/comments/5trkew/release_uwpstreamer_wpf_edition_net_462/) but still find it puzzling:


_The Windows Store (UWPStreamer) version uses [DatagramSocket](https://docs.microsoft.com/en-us/uwp/api/Windows.Networking.Sockets.DatagramSocket)  whereas the WPF edition uses [UDPClient](https://msdn.microsoft.com/en-us/library/system.net.sockets.udpclient.aspx) for receiving frames._

_In testing, I noticed that frames dropped if the battery was low on the 3DS or if someone was watching Netflix or battering the network in some way.  Barring either of these scenarios it would be expected that the performance should be similar, however, there may be a delay incurred due to differences in the underlying APIs used for each platform._

_FWIW, you could rule out external influence further by directly connecting to the pc using Windows 10's built-in Wifi sharing mentioned [here](https://www.reddit.com/r/3dshacks/comments/5t0l2u/update_uwpstreamer_now_with_builtin_support_for/ddm3xb3/).  Wouldn't be surprised if you got the same result though._ 

Here are the settings I typically use with UWPStreamer:
Screen Priority = Top Screen
Priority Factor = 1 (sometimes 2)
Image Quality = 75 (sometimes 80)
QoS Value = 15

While this does not directly answer your question, it may help zone in on a root cause.  Does any of this raise a flag to you?

**Comment by Astrallys** [comment]
that's a huge text but i have read it. I already know all of this ( read everything i have found before testing ) 
But the low framerates is weird right ? Of course less Image Quality = better fps but as the name say : Lower quality. ( 75 is correct but i would be surprise to see how many fps you get with that ? )
Maybe it's just a problem with me. But with all the settings i have used that's weird to never get a 30fps :/

**Comment by toolboc** [comment]
@Astrallys , it is possible that this may be an isolated issue.  

Here are a few YouTube vids showing various users getting good FPS with UWPStreamer:
[Play 3DS On Xbox One! | UWPStreamer showcase](https://www.youtube.com/watch?v=mO7kZx6YRTU&t=1s)
[Poochy & Yoshi's Woolly World | No More Beta Reviews ](https://www.youtube.com/watch?v=9HNBWVT911o0)
[Paper Mario: Sticker Star New Nintendo 3DS Stream Pt 8 ](https://www.youtube.com/watch?v=_2a9jvRlJtg)

Another thing to consider is the game(s) that you may be trying to play.  I know some games (Smash Bros., Monster Hunter) tax the CPU a bit harder and can reduce NTR's ability to generate and send frames.

We could also try to ask https://www.reddit.com/user/_pixelheart what settings are being used in his recordings.  This might assist in getting to the bottom of better overall settings.

**Comment by Astrallys** [comment]
i already saw all of those videos. That's why i don't know but after a little test when we upload the video to YouTube, if the record is with 25 fps after uploading it. We see a smoother video ( i don't know how to explain, French so i do my best ) 

Know for monster hunter etc..  i 'm waiting for an answer from pixelheart. but i think he have used a quality of 100 because no blurry thing around the letter ( i have paused the video when the text in game is shown )

i will try to found something who can fps overlay the app

**Comment by toolboc** [comment]
@Astrallys ,

FPS could be counted by initiating a 1 second timer in the `TryDisplayImage` method of [NTR.cs](https://github.com/toolboc/UWPStreamer/blob/master/UWPStreamer/Services/NTR.cs) then counting frames for each screen and clearing that value on each timer tick.  You would of course have a different FPS value for each screen.  

To visualize, you could bind those FPS values to a textblock in [MainPage.xaml](https://github.com/toolboc/UWPStreamer/blob/master/UWPStreamer/MainPage.xaml) and finally would be a good idea to implement logic to enable/disable in the [MainPage.xaml.cs](https://github.com/toolboc/UWPStreamer/blob/master/UWPStreamer/MainPage.xaml.cs).

**Comment by Astrallys** [comment]
I found something, i monitoring the fps with Action Mirillis ( that show the fps ) i'm at 30 with your settings but it's like a suttering. i have tested all my internet connexion and no problem from that.  Do you know if it is possible to lock the fps at 30 ? that can maybe help to get a constant framerate/

**Comment by toolboc** [comment]
@Astrallys , locking the framerate is a great idea!  I believe this could be done in the` TryDisplayImage ` method of NTR.cs as described above, the basic idea being to stop drawing frames once a certain threshold is reached.  I wonder if this would actually cause more stuttering though.  For example, imagine 30 frames come in, then a halt, then 30 more etc.  This could be reduced with a smoothing function but may become complicated in practice due to inconsistencies in network / send rate.

Are you able to pull down the code and build on a local machine?  This would be an interesting experiment to explore.

**Comment by Astrallys** [comment]
I know nothing about coding. But i give a try this week-end if i can help :) 
i can try to add interpolation ( i know it's something different )whithout interacting with the frames

**Comment by toolboc** [comment]
I would be happy to help in getting a dev environment setup.  If you have a desire to learn, we can make something happen =)

**Comment by Astrallys** [comment]
Hello,

Sorry for late respond. I have tried to install the WPF Performance Suite
but after installing : Microsoft Windows SDK for Windows 10 and .NET
Framework 4        ( with   WPF Performance Suite ) selected he's not found
on my pc.


2017-06-02 17:17 GMT+02:00 Paul DeCarlo <notifications@github.com>:

**Comment by toolboc** [comment]
The WPF Performance Suite will report back the application's overall framerate, not the frames being received from NTR.  In order to do that, you will need to watch the critical code areas mentioned in previous reply.

To analyze at the code level, you will need to install Visual Studio 2015 or higher,  Community edition is fine => http://visualstudio.com .  This will allow you to build and modify the source code for UWP/WPFStreamer which is where the issue would be both measured and remedied.

If you have issues setting up VS and building source please reply back with a screenshot and I would be happy to help.

**Comment by Astrallys** [comment]
It's ok, i have needed to use a patch since there is not really incorporate
on Windows 10 version.

2017-06-08 18:28 GMT+02:00 Paul DeCarlo <notifications@github.com>:

**Comment by Astrallys** [comment]
I check With Performance Suite the framerat in idle and when a game is
running ( and compare with the Action Mirillis fps overlay to see if there
is the same framerate or no ), after that, i try to see if i can made a
constant 30fps.

2017-06-08 18:34 GMT+02:00 Eric Delattre <nocommentary62@gmail.com>:

**Comment by Astrallys** [comment]
So, the WPF version as like 1fps drops every 10seconds (i don't know why
)but the UWP version run smooth at 30fps constant on Monster Hunter(
without any changes )

2017-06-08 18:45 GMT+02:00 Eric Delattre <nocommentary62@gmail.com>:

**Comment by toolboc** [comment]
Interesting, wasn't the original issue with UWPStreamer?

> well, the low fps are only with UWPStreamer.. Watever the settings i used. ( compared to kit-kat ) the fps are always bad here :/

**Comment by toolboc** [comment]
Interesting, wasn't the original issue with UWPStreamer only?
well, the low fps are only with UWPStreamer.. Watever the settings i used. ( compared to kit-kat ) the fps are always bad here :/

**Comment by toolboc** [comment]
Interesting, wasn't the original issue with UWPStreamer only?

> well, the low fps are only with UWPStreamer.. Watever the settings i used. ( compared to kit-kat ) the fps are always bad here :/

**Comment by Astrallys** [comment]
I was thinking but no that' just with the WPF version. Also i have tried to
add the constant 30fps but that not work properly. The fps still variable,
that only lock the screen view at 30fps.

2017-06-09 3:42 GMT+02:00 Paul DeCarlo <notifications@github.com>:

**Comment by Astrallys** [comment]
> Have you notice, UWPstreamer and WPFStreamer are blurry compared to kit-kat ? but les pixels

Technically, kit-kat is a wrapper over NTRViewer which assembles frames sent by NTR in the same way as UWPStreamer.  Given that the image data sent from NTR is the same in both applications, this should not be an issue.  There may be blurriness experienced when images are resized larger due to stretching of pixels.  Can you provide a screenshot of a side by side comparison?

**Comment by Astrallys** [comment]
Hi,
I cannot open the master build on Visual Studio, too many error on the
master build.

2017-06-09 16:01 GMT+02:00 Eric Delattre <nocommentary62@gmail.com>:

**Comment by Astrallys** [comment]
There is missing files on the master folder. Can you update it ?
Thanks,

2017-06-09 18:30 GMT+02:00 Eric Delattre <nocommentary62@gmail.com>:

**Comment by toolboc** [comment]
> I cannot open the master build on Visual Studio, too many error on the master build

> There is missing files on the master folder. Can you update it ?

I just pulled down a fresh copy of the repo from GitHub and the project built successfully on my end.  

![image](https://user-images.githubusercontent.com/2018336/27186981-99c1a5f6-51af-11e7-96a0-bc76b36b8c10.png)

Have you installed VS 2015 or greater and installed the [tools for Win 10 development](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk)?  

Can you provide a screenshot of the issues you are encountering?

**Comment by Astrallys** [comment]
Both are installed but those errors

2017-06-15 16:47 GMT+02:00 Paul DeCarlo <notifications@github.com>:

**Comment by toolboc** [comment]
> Both are installed but those errors

Screenshot?
